### ISSUE TITLE
Fix: .env files must be hidden for many security problems.

### ISSUE THREAD

**Issue by bgebes** [menesdev/Blogify#1]
Dear @menesdev,

I visited your profile and a few repositories. You're doing perfect this work. But, you should check your security bugs. There is an [.env file](https://github.com/menesdev/Blogify/blob/main/server/.env) that contains MongoDB API Connection from this repository. All of the developers prefer to hide this file for many security problem. That starts with dot(.) which means that should be hidden. You may hide this private data files with [.gitignore method](https://git-scm.com/docs/gitignore). You may do research many things about that.  You may change your MongoDB API connection then re-commit it with applied .gitignore method. You should be careful more than from now. :+1:

With Respect,
Have a nice days.

**Comment by menesdev** [comment]
Thank u very much for your advice Berkay.
